project:
  type: website
  output-dir: docs

website:
  title: "blog"
  site-url: https://brainworkup.org/blog/
  image: images/logo.png
  favicon: images/favicon.png
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cyborg
    css: src/styles.css
