project:
  type: website
  output-dir: docs

website:
  title: "bwu blog"
  site-url: https://brainworkup.org/blog/
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cyborg
    css: src/styles.css
